### ISSUE TITLE
AmbevTech e RedVentures

### ISSUE THREAD

**Issue by romiof** [AfonsoFeliciano/Empresas-Brasileiras-Trabalho-Remoto#7]
Empresa: AmbevTech
Site: https://www.ambevtech.com.br/
Modalidade: Home office e híbrido

Empresa: Red Ventures Brasil
Site: https://redventures.com.br/
Modalidade: Home office

**Comment by AfonsoFeliciano** [comment]
Muito obrigado pela contribuição. Empresas adicionadas.
